steps:
- label: build image with cnb buildpack
  agents:
    queue: kubernetes
  plugins:
  - kubernetes:
      podSpec:
        containers:
        - image: gcr.io/buildpacks/builder:latest
          command: [.buildkite/steps/image.sh]
          volumeMounts:
          - mountPath: /home/cnb/.docker
            name: ghcr-secret
        volumes:
        - name: ghcr-secret
          secret:
            secretName: ghcr-secret
